"""Add manager in cafe

Revision ID: bae69e1e3244
Revises: fcfa66a24dc7
Create Date: 2025-08-06 21:02:48.815826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bae69e1e3244'
down_revision: Union[str, Sequence[str], None] = 'fcfa66a24dc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cafes', sa.Column('manager_id', sa.Integer(), nullable=True, comment='ID менеджера кофейни'))
    op.create_foreign_key(None, 'cafes', 'users', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cafes', type_='foreignkey')
    op.drop_column('cafes', 'manager_id')
    # ### end Alembic commands ###
