"""Add first migration

Revision ID: fcfa66a24dc7
Revises: 
Create Date: 2025-08-06 21:01:19.558774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcfa66a24dc7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cafes',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Название кофейни'),
    sa.Column('city', sa.String(length=100), nullable=False, comment='Город'),
    sa.Column('address', sa.String(length=255), nullable=False, comment='Адрес'),
    sa.Column('open_time', sa.Time(), nullable=False),
    sa.Column('close_time', sa.Time(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='Телефон в формате 1234567890'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Статус активности кофейни'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shifts',
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('barista_count', sa.Integer(), nullable=False),
    sa.Column('cafe_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False, comment='Telegram ID пользователя'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Полное имя пользователя'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='Телефон в формате 1234567890'),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'BARISTA', name='role'), nullable=False, comment='Роль пользователя'),
    sa.Column('password', sa.CHAR(length=60), nullable=True, comment='Пароль минимум 6 символов'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Статус активности: подтвержден/заблокирован'),
    sa.Column('cafe_id', sa.Integer(), nullable=True, comment='ID кофейни, к которой привязан пользователь'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('reservations',
    sa.Column('barista_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('reserved', 'attended', 'cancelled', 'onconfirm', name='status'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['barista_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservations')
    op.drop_table('users')
    op.drop_table('shifts')
    op.drop_table('cafes')
    # ### end Alembic commands ###
