name: Основной рабочий процесс
on:
  push:
    branches:
    - main
jobs:
    # backend_tests:
    #   permissions: 
    #     contents: read
    #   name: Проверка
    #   runs-on: ubuntu-latest
    #   steps:
    #     - name: Получение исходного кода из репозитория
    #       uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    #     - name: Установка пайтон
    #       uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b
    #       with:
    #         python-version: 3.12.10
    #     - name: Установка зависимостей
    #       run: |
    #         python -m pip install --upgrade pip 
    #         pip install -r ./src/requirements.txt
    #     - name: Проверяем код с помощью ruff
    #       run: python -m ruff check
    push_to_dockerhub_web:
      permissions: 
        contents: read
      name: Отправка образа web
      runs-on: ubuntu-latest
      # needs: backend_tests
      steps:
        - name: Получение исходного кода из репозитория
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        - name: Установка сборщика контейнеров Docker
          uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5
        - name: Авторизация на Docker Hub
          uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
          with:
            username: ${{ secrets.DOCKER_USERNAME }} 
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Одновременный билд и пуш образа в Docker Hub
          uses: docker/build-push-action@67a2d409c0a876cbe6b11854e3e25193efe4e62d
          with:
            context: ./src/
            push: true
            tags: kasyak999/test_skuratov_coffee_team1_web:latest
    push_to_dockerhub_redis:
      permissions: 
        contents: read
      name: Отправка образа redis
      runs-on: ubuntu-latest
      # needs: backend_tests
      steps:
        - name: Получение исходного кода из репозитория
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        - name: Установка сборщика контейнеров Docker
          uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5
        - name: Авторизация на Docker Hub
          uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
          with:
            username: ${{ secrets.DOCKER_USERNAME }} 
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Одновременный билд и пуш образа в Docker redis
          uses: docker/build-push-action@67a2d409c0a876cbe6b11854e3e25193efe4e62d
          with:
            context: ./src/redis/
            push: true
            tags: kasyak999/test_skuratov_coffee_team1_redis:latest
    push_to_dockerhub_nginx:
      permissions: 
        contents: read
      name: Отправка образа nginx
      runs-on: ubuntu-latest
      # needs: backend_tests
      steps:
        - name: Получение исходного кода из репозитория
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        - name: Установка сборщика контейнеров Docker
          uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5
        - name: Авторизация на Docker Hub
          uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
          with:
            username: ${{ secrets.DOCKER_USERNAME }} 
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Одновременный билд и пуш образа в Docker nginx
          uses: docker/build-push-action@67a2d409c0a876cbe6b11854e3e25193efe4e62d
          with:
            context: ./src/nginx/
            push: true
            tags: kasyak999/test_skuratov_coffee_team1_nginx:latest

            